### ISSUE TITLE
Better names

### ISSUE THREAD

**Issue by RobCannon** [DarqueWarrior/team#1]
Hey, your first issue!
Can I suggest that you use more specific names to avoid name collisions.  Since PowerShell auto-imports modules now, the likelihood of a name collision is much higher.  So, instead of Get-Queue, how about Get-TeamQueue. 

Basically, make every command "Verb-TeamNoun".

I just got finished working on some PowerShell automation for VSTS, so I will be happy to submit some more command once the code shows up.

**Comment by brettjacobson** [comment]
We've experienced this name collision ourselves; I've written some PoSH cmdlets for working with Service Bus for Windows Server (on premises Azure Service Bus), and had that exact problem with Get-Queue, and I named mine Get-SBQueue, using a SB prefix (because ServiceBus was too long to type!).

**Comment by DarqueWarrior** [comment]
I was trying to keep the names short because some are already really long.  You can actually add a prefix when you import the module with the -Prefix parameter.  I understand this will not be much help for automatically imported modules. 

As a workaround you could add the following line to your PowerShell profile script
Remove-Module Team; Import-Module Team -Prefix Team

I will consider changing the names. I just hate to make them longer than they have to be.

Thanks for the feedback.

**Comment by mmajcica** [comment]
How about changing names as @RobCannon suggested and assign aliases to the cmdlets?

Something like:

```
function Get-TeamQueue
{
    [CmdletBinding()]
    [Alias("GTQ")]
    PARAM (
        $Param1
    )
```

**Comment by DarqueWarrior** [comment]
I will give this some more consideration. Which module are the names conflicting with?

**Comment by RobCannon** [comment]
I thought it was going to conflict the  MSMQ commands, but those are namespaces with Get-MsmqQueue.  But the names help discoverability.  If I am at the command line and I type Get-Team...  The intellisense will show me all of the commands associated with the Team module.

**Comment by DarqueWarrior** [comment]
OK. That will be a breaking change for anyone already using the module so let me find a good time for this type of change.
